## I.Struktur Data  
1.List

In [1]:
aList = ["John", 33,"Toronto", True]

In [2]:
aList

['John', 33, 'Toronto', True]

In [3]:
type(aList)

list

In [4]:
bin_colors=['Red','Green','Blue','Yellow']

## 2.Tuples

In [7]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [8]:
print(f"The element after third element onwards are {bin_colors[2:]}")

The element after third element onwards are ('Blue', 'Yellow')


In [10]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


## 3.Dictionary

In [12]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [13]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [14]:
bin_colors.get('approved_color')

'Green'

In [15]:
bin_colors['approved_color']

'Green'

In [16]:
bin_colors['approved_color']="purple"

In [17]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'purple', 'refused_color': 'Red'}


## 4.Sets

In [19]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [23]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [24]:
print(f"The union of yellow and red sets is {yellow|red}")

The union of yellow and red sets is {'blood', 'rose', 'leaves', 'fire hydrant', 'dandelions'}


In [25]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'fire hydrant', 'leaves'}


## 5.DataFrames

In [27]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


## 1.41.1 Column Selection

In [29]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [30]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

## 1.4.2 Row Selection

In [32]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [33]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

## 6. Matrix
 1.5 Matrix

In [35]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21,22,23], [31, 32, 33]])

In [36]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [37]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [38]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

## Tipe Data Abstrak
1. Vector

## Vector

In [40]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [41]:
print(type(myVector))

<class 'list'>


In [42]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [43]:
print(type(myVector))

<class 'numpy.ndarray'>


## 2. Stack

In [49]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(size):
        return len(self.items)

##         Populate the Stack

In [50]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")


##  POP

In [51]:
stack.pop()

'Yellow'

In [52]:
stack.isEmpty()

False

In [53]:
colors = ['Red']

In [54]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [55]:
colors

['Red', 'Green', 'Yellow', 'Blue']

###    3. Queue

## Queue

In [61]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)
        

In [62]:
queue = Queue()

In [63]:
queue.enqueue("Red")

In [65]:
queue.enqueue('Green')

In [66]:
queue.enqueue('Blue')

In [67]:
queue.enqueue('Yellow')

In [68]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [69]:
print(queue.dequeue())

Red
